config/routes.rb
FinderProductsSupermarket::Application.routes.draw do
  resources :cart, only: :show do
    put 'add_to/:product_supermarket_id', to: 'cart#add', as: :add_to
    put 'remove_from/:product_supermarket_id', to: 'cart#remove', as: :remove_from
    collection do
      get 'product_supermarkets_selected'
    end
  end
  resources :supermarkets do
    resources :aisles, except: :show
  end
  resources :brands, except: [:show, :index]
  resources :worlds, except: [:show, :index]
  resources :finder_products, only: :index do
    match "/new" => "finder_products#new", via: :post, on: :collection
    collection do
      get "selected"
      get "suggested"
      get "show_product_in_gondola"
      get "in_cart"
    end
  end
  resources :association_rules do
    member do
      get 'flare'
      get 'paginate'
      get 'show_products_in_layout'
      get 'paths'
    end
  end
  resources :lists, only: [:index, :create] do
    match "/new" => "lists#new", via: :post, on: :collection
    match "/destroy" => "lists#destroy", via: :delete, on: :member
    match "/add_products" => "lists#add_products", via: :put, on: :collection
    match "/destroy_product" => "lists#destroy_product", via: :delete, on: :collection
  end
  resources :gondolas, except: :index do
    collection do
      get 'points_from'
    end
  end
  resources :products, except: :index do
    resources :gondola_products, except: :show
    resources :product_supermarkets, except: :show
  end
  resources :categories, except: [:show, :index] do
    resources :sub_categories, except: :show
    member do
      get 'update_sub_categories'
    end
  end
  resources :admin, only: :index do
    collection do
      get 'users'
      get 'categories'
      get 'aisles'
      get 'gondolas'
      get 'products'
      get 'worlds'
      get 'brands'
      get 'supermarkets'
      get 'messages'
      get 'message'
    end
  end
  resources :person_profiles, only: [:update, :edit]
  resources :search, only: :index do
    collection do
      get 'paginate'
      get 'selected'
      get 'update_sub_categories'
    end
  end
  devise_for :users
  match "/about_us" => "static_pages#about_us", as: :about_us
  match "/contact_us" => "static_pages#contact_us", as: :contact_us
  match "/how_fpsm_works" => "static_pages#how_fpsm_works", as: :how_fpsm_works
  match "/submit_message" => "static_pages#submit_message", as: :submit_message, via: :post
  root to: 'static_pages#index'

  match 'auth/:provider/callback', to: 'authentications#create'
  match 'auth/failure', to: redirect('/')
  match 'signout', to: 'authentications#destroy', as: 'signout'
end

app/models/aisle.rb
class Aisle < ActiveRecord::Base
  attr_accessible :name, :number, :state

  belongs_to :supermarket
  has_many :gondolas, dependent: :destroy

  paginates_per 10

  validates_presence_of :name

  def number_name
    "#{ number } - #{ name }"
  end
end

app/controllers/aisles_controller.rb
class AislesController < ApplicationController
  layout 'admin'

  before_filter :authenticate_user!
  before_filter :only_admin
  before_filter :find_supermarket

  def index
    @aisles = @supermarket.aisles.page(params[:page])
  end

  def new
    @aisle = Aisle.new
  end

  def edit
    @aisle = Aisle.find(params[:id])
  end

  def create
    @aisle = @supermarket.aisles.build(params[:aisle])

    if @aisle.save
      flash[:notice] = 'Pasillo fue satisfactoriamente creado.'
      redirect_to supermarket_aisles_path(@supermarket)
    else
      render action: "new"
    end
  end

  def update
    @aisle = Aisle.find(params[:id])

    if @aisle.update_attributes(params[:aisle])
      flash[:notice] = 'Pasillo fue satisfactoriamente actualizado.'
      redirect_to supermarket_aisles_path(@supermarket)
    else
      render action: "edit"
    end
  end

  def destroy
    @aisle = Aisle.find(params[:id])
    @aisle.destroy

    flash[:notice] = 'Pasillo fue satisfactoriamente eliminado.'
    redirect_to supermarket_aisles_path(@supermarket)
  end

  private

  def find_supermarket
    @supermarket = Supermarket.find(params[:supermarket_id])
  end
end

app/helpers/aisles_helper.rb
module AislesHelper
end

app/views/aisles/_form.html.erb
<%= form_for([@supermarket, @aisle], html: { role: "form", class: "form-horizontal" }) do |f| %>
  <%= error_messages!(@aisle) %>
  <div class="form-group">
    <div class="col-sm-12">
      <%= f.text_field :name, autofocus: true, class: "form-control", placeholder: "Nombre" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-12">
      <%= f.number_field :number, min: 1, class: "form-control", placeholder: "Número" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-12">
      <div class="checkbox">
        <label>
          <%= f.check_box :state %>
          Activo
        </label>
      </div>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-12">
      <%= button_tag class: "btn btn-default", type: "submit" do %>
        <i class="glyphicon glyphicon-floppy-disk"></i>
        Guardar
      <% end %>
      <%= link_to supermarket_aisles_path(@supermarket), class: "btn btn-info" do %>
        <i class="glyphicon glyphicon-arrow-left"></i>
        Regresar
      <% end %>
    </div>
  </div>
<% end %>

app/views/aisles/edit.html.erb
<%= stylesheet "/stylesheets/admin.css" %>
<div class="row content">
  <div class="col-md-offset-3 col-md-6">
    <h3>Editando Pasillo</h3>
    <%= render 'form' %>
  </div>
</div>

app/views/aisles/index.html.erb
<%= stylesheet "/stylesheets/admin.css" %>
<div class="row content">
  <h4><%= page_entries_info @aisles %></h4>
  <div class="mb20">
    <%= link_to new_supermarket_aisle_path(@supermarket), class: "btn btn-success" do %>
      <i class="glyphicon glyphicon-plus"></i>
      Nuevo Pasillo
    <% end %>
    <%= link_to supermarkets_admin_index_path, class: "btn btn-info" do %>
      <i class="glyphicon glyphicon-arrow-left"></i>
      Regresar
    <% end %>
  </div>
  <% if @aisles.any? %>
    <div class="table-responsive">
      <table class="table table-bordered">
        <thead>
          <tr>
            <th>Número</th>
            <th>Nombre</th>
            <th>Acciones</th>
          </tr>
        </thead>
        <tbody class="table-hover">
          <% @aisles.each do |aisle| %>
            <tr>
              <td><%= aisle.number %></td>
              <td><%= aisle.name %></td>
              <td>
                <%= link_to edit_supermarket_aisle_path(@supermarket, aisle), class: "btn btn-warning" do %>
                  <i class="glyphicon glyphicon-pencil"></i>
                  Editar
                <% end %>
                <%= link_to supermarket_aisle_path(@supermarket, aisle), method: :delete, data: { confirm: '¿Estás seguro?' }, class: "btn btn-danger" do %>
                  <i class="glyphicon glyphicon-remove"></i>
                  Eliminar
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <%= paginate @aisles %>
  <% end %>
</div>

app/views/aisles/new.html.erb
<%= stylesheet "/stylesheets/admin.css" %>
<div class="row content">
  <div class="col-md-offset-3 col-md-6">
    <h3>Nuevo Pasillo</h3>
    <%= render 'form' %>
  </div>
</div>