config/routes.rb
FinderProductsSupermarket::Application.routes.draw do
  resources :cart, only: :show do
    put 'add_to/:product_supermarket_id', to: 'cart#add', as: :add_to
    put 'remove_from/:product_supermarket_id', to: 'cart#remove', as: :remove_from
    collection do
      get 'product_supermarkets_selected'
    end
  end
  resources :supermarkets do
    resources :aisles, except: :show
  end
  resources :brands, except: [:show, :index]
  resources :worlds, except: [:show, :index]
  resources :finder_products, only: :index do
    match "/new" => "finder_products#new", via: :post, on: :collection
    collection do
      get "selected"
      get "suggested"
      get "show_product_in_gondola"
      get "in_cart"
    end
  end
  resources :association_rules do
    member do
      get 'flare'
      get 'paginate'
      get 'show_products_in_layout'
      get 'paths'
    end
  end
  resources :lists, only: [:index, :create] do
    match "/new" => "lists#new", via: :post, on: :collection
    match "/destroy" => "lists#destroy", via: :delete, on: :member
    match "/add_products" => "lists#add_products", via: :put, on: :collection
    match "/destroy_product" => "lists#destroy_product", via: :delete, on: :collection
  end
  resources :gondolas, except: :index do
    collection do
      get 'points_from'
    end
  end
  resources :products, except: :index do
    resources :gondola_products, except: :show
    resources :product_supermarkets, except: :show
  end
  resources :categories, except: [:show, :index] do
    resources :sub_categories, except: :show
    member do
      get 'update_sub_categories'
    end
  end
  resources :admin, only: :index do
    collection do
      get 'users'
      get 'categories'
      get 'aisles'
      get 'gondolas'
      get 'products'
      get 'worlds'
      get 'brands'
      get 'supermarkets'
      get 'messages'
      get 'message'
    end
  end
  resources :person_profiles, only: [:update, :edit]
  resources :search, only: :index do
    collection do
      get 'paginate'
      get 'selected'
      get 'update_sub_categories'
    end
  end
  devise_for :users
  match "/about_us" => "static_pages#about_us", as: :about_us
  match "/contact_us" => "static_pages#contact_us", as: :contact_us
  match "/how_fpsm_works" => "static_pages#how_fpsm_works", as: :how_fpsm_works
  match "/submit_message" => "static_pages#submit_message", as: :submit_message, via: :post
  root to: 'static_pages#index'

  match 'auth/:provider/callback', to: 'authentications#create'
  match 'auth/failure', to: redirect('/')
  match 'signout', to: 'authentications#destroy', as: 'signout'
end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :gondolas_count, :name, :state, :world_id, :xstart, :xend, :ystart, :yend

  has_many :sub_categories, dependent: :destroy
  belongs_to :aisle
  belongs_to :world, counter_cache: true

  paginates_per 10

  validates_presence_of :name, :xend, :xstart, :yend, :ystart, :world_id
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  before_filter :authenticate_user!

  def index
    @supermarket = Supermarket.find(params[:supermarket_id])
    @categories = Category.all
    @brands = Brand.all
  end

  def paginate
    @product_supermarkets = response_scope
    @product_supermarkets = @product_supermarkets.page(params.has_key?(:page) ? params[:page] : 1).per(9)
    render layout: false
  end

  def selected
    product = Product.find(params[:product_id])
    render partial: "selected", locals: { product: product }
  end

  def update_sub_categories
    @sub_categories = SubCategory.where(category_id: params[:category_id]).order(:name)
    render layout: false
  end

  private

  def response_scope
    product_supermarkets = ProductSupermarket.scoped(
      conditions: ["product_supermarkets.supermarket_id = ?", params[:supermarket_id]]
    )

    if params[:product].present?
      product_supermarkets = product_supermarkets.scoped(
        include: [:product],
        conditions: [
          ActiveRecord::Base.connection.adapter_name == "PostgreSQL" ? "products.name ILIKE :val" : "products.name LIKE :val",
          { val: "%#{ params[:product] }%" }
        ]
      )
    end

    if params.has_key?(:category_id)
      product_supermarkets = product_supermarkets.scoped(
        include: [product: :sub_category],
        conditions: ["sub_categories.category_id = ?", params[:category_id]]
      )
    end

    if params.has_key?(:sub_category_ids)
      product_supermarkets = product_supermarkets.scoped(
        include: [product: :sub_category],
        conditions: ["sub_categories.id IN (?)", params[:sub_category_ids]]
      )
    end

    if params.has_key?(:brand_ids)
      product_supermarkets = product_supermarkets.scoped(
        include: [product: :brand],
        conditions: ["sizes.id IN (?)", params[:brand_ids]]
      )
    end

    if params.has_key?(:price_ids)
      product_supermarkets = product_supermarkets.scoped(
        conditions: [condition_for_price(params[:price_ids])]
      )
    end

    order_by =
      case params[:order_by]
      when "1" then "product_supermarkets.unit_price DESC"
      when "2" then "product_supermarkets.unit_price ASC"
      when "3" then "product_supermarkets.created_at DESC"
      end

    product_supermarkets = product_supermarkets.scoped(
      order: order_by
    )

    product_supermarkets
  end

  def condition_for_price(price_ids)
    conditions = []

    price_ids.each do |p_id|
      condition =
        case p_id
        when "1" then "(product_supermarkets.unit_price >= 1 AND product_supermarkets.unit_price <= 10)"
        when "2" then "(product_supermarkets.unit_price >= 10 AND product_supermarkets.unit_price <= 25)"
        when "3" then "(product_supermarkets.unit_price >= 25 AND product_supermarkets.unit_price <= 50)"
        when "4" then "(product_supermarkets.unit_price >= 50 AND product_supermarkets.unit_price <= 100)"
        when "5" then "(product_supermarkets.unit_price >= 100 AND product_supermarkets.unit_price <= 200)"
        end
      conditions << condition
    end

    conditions.join(" OR ")
  end
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/search/_filter.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    Filtrar búsqueda por:
  </div>
  <%= hidden_field_tag "supermarket_id", @supermarket.id %>
  <div class="panel-body">
    <div class="form-group">
      <%= text_field_tag "product", nil, class: "form-control", placeholder: "Producto", autofocus: true %>
    </div>
    <div class="form-group">
      <%= button_tag class: "btn btn-danger fr", type: "submit", id: "search" do %>
        <i class="glyphicon glyphicon-search"></i>
        Buscar
      <% end %>
    </div>
  </div>
  <div class="panel-heading body-title">Categorías</div>
  <div class="panel-body">
    <div class="scroll-y">
      <% @categories.each do |category| %>
        <label>
          <%= radio_button_tag "category_id", category.id %>
          <%= category.name %>
        </label>
        <br>
      <% end %>
    </div>
  </div>
  <div class="panel-heading body-title sub_categories">Sub Categorías</div>
  <div class="panel-body sub_categories" id="sub_categories">
  </div>
  <div class="panel-heading body-title">Marcas</div>
  <div class="panel-body">
    <div class="scroll-y">
      <% @brands.each do |brand| %>
        <label>
          <%= check_box_tag "brand_ids[]", brand.id %>
          <%= brand.name %>
        </label>
        <br>
      <% end %>
    </div>
  </div>
  <div class="panel-heading body-title">Precio</div>
  <div class="panel-body">
    <div class="scroll-y">
      <label>
        <%= check_box_tag "price_ids[]", 1  %> S/. 1.00 - S/. 10.00
      </label>
      <br>
      <label>
        <%= check_box_tag "price_ids[]", 2  %> S/. 10.00 - S/. 25.00
      </label>
      <br>
      <label>
        <%= check_box_tag "price_ids[]", 3  %> S/. 25.00 - S/. 50.00
      </label>
      <br>
      <label>
        <%= check_box_tag "price_ids[]", 4  %> S/. 50.00 - S/. 100.00
      </label>
      <br>
      <label>
        <%= check_box_tag "price_ids[]", 5  %> S/. 100.00 - $/. 200.00
      </label>
      <br>
    </div>
  </div>
</div>

app/views/search/index.html.erb
<%= stylesheet "/stylesheets/static_pages.css" %>
<%= stylesheet "/stylesheets/search.css" %>
<%= javascript "/javascripts/search.js" %>
<div class="row content">
  <h3 class="supermarket">Productos de <%= @supermarket.name %></h3>
  <div class="actions">
    <%= link_to supermarkets_path, class: "btn btn-default" do %>
      <i class="glyphicon glyphicon-arrow-left"></i>
      Regresar
    <% end %>
    <%= form_tag new_lists_path, id: "add-to-list" do %>
      <button type="submit" class="btn btn-success">
        <i class="glyphicon glyphicon-list-alt"></i>
        Crear lista
      </button>
    <% end %>
  </div>
  <hr>
  <div class="col-lg-3 col-md-3 col-xs-12" id="filter">
    <%= render "filter" %>
  </div>
  <div class="col-lg-9 col-md-9 col-xs-12">
    <div class="row" id="products_suggested"></div>
    <div id="order_by" class="mb20">
      <strong class="mr10">Ordenar por:</strong>
      <%= link_to "Precio mas alto a mas bajo", "#", class: "active", data: { order_id: 1 } %>
      &#124;
      <%= link_to "Precio mas bajo a mas alto", "#", data: { order_id: 2 } %>
      &#124;
      <%= link_to "Agregados recientemente", "#", data: { order_id: 3 } %>
    </div>
    <div id="products"></div>
  </div>
</div>

app/views/search/paginate.html.erb
<% if @product_supermarkets.any? %>
  <% k = 0 %>
  <% @product_supermarkets.each_with_index do |product_supermarket, index| %>
    <% if index % 3 == 0 %>
      <div class="row mb20">
    <% end %>
    <div class="col-sm-4">
      <div class="product">
        <div class="pay">
          <div class="price">
            <%= number_to_currency(product_supermarket.unit_price) %>
          </div>
        </div>
        <%= image_tag product_supermarket.product.link, class: "img-thumbnail", style: "height:250px;" %>
        <div class="cart">
          <div class="action">
            <%= link_to "", class: "btn btn-danger fr", data: { target: product_supermarket.cart_action(current_user.id), addUrl: cart_add_to_path(current_user.id, product_supermarket), removeUrl: cart_remove_from_path(current_user.id, product_supermarket) } do %>
              <i class="glyphicon glyphicon-shopping-cart"></i>
              <span>
                <%= product_supermarket.cart_action(current_user.id) %>
              </span> Carro
            <% end %>
          </div>
        </div>
        <div class="fix_clear"></div>
        <div class="text1 col4">
          <%= product_supermarket.product.name %>
        </div>
        <p>
          <%= product_supermarket.product.description %>
        </p>
      </div>
    </div>
    <% k += 1 %>
    <% if k % 3 == 0 || @product_supermarkets.count == index + 1 %>
      <% k = 0 %>
      </div>
    <% end %>
  <% end %>
  <%= paginate @product_supermarkets %>
  <div class="fix_clear"></div>
<% end %>

app/views/search/update_sub_categories.html.erb
<% if @sub_categories.any? %>
  <div class="scroll-y">
    <% @sub_categories.each do |sub_category| %>
      <label>
        <%= check_box_tag "sub_category_ids[]", sub_category.id %>
        <%= sub_category.name %>
      </label>
      <br>
    <% end %>
  </div>
<% end %>