config/routes.rb
FinderProductsSupermarket::Application.routes.draw do
  resources :cart, only: :show do
    put 'add_to/:product_supermarket_id', to: 'cart#add', as: :add_to
    put 'remove_from/:product_supermarket_id', to: 'cart#remove', as: :remove_from
    collection do
      get 'product_supermarkets_selected'
    end
  end
  resources :supermarkets do
    resources :aisles, except: :show
  end
  resources :brands, except: [:show, :index]
  resources :worlds, except: [:show, :index]
  resources :finder_products, only: :index do
    match "/new" => "finder_products#new", via: :post, on: :collection
    collection do
      get "selected"
      get "suggested"
      get "show_product_in_gondola"
      get "in_cart"
    end
  end
  resources :association_rules do
    member do
      get 'flare'
      get 'paginate'
      get 'show_products_in_layout'
      get 'paths'
    end
  end
  resources :lists, only: [:index, :create] do
    match "/new" => "lists#new", via: :post, on: :collection
    match "/destroy" => "lists#destroy", via: :delete, on: :member
    match "/add_products" => "lists#add_products", via: :put, on: :collection
    match "/destroy_product" => "lists#destroy_product", via: :delete, on: :collection
  end
  resources :gondolas, except: :index do
    collection do
      get 'points_from'
    end
  end
  resources :products, except: :index do
    resources :gondola_products, except: :show
    resources :product_supermarkets, except: :show
  end
  resources :categories, except: [:show, :index] do
    resources :sub_categories, except: :show
    member do
      get 'update_sub_categories'
    end
  end
  resources :admin, only: :index do
    collection do
      get 'users'
      get 'categories'
      get 'aisles'
      get 'gondolas'
      get 'products'
      get 'worlds'
      get 'brands'
      get 'supermarkets'
      get 'messages'
      get 'message'
    end
  end
  resources :person_profiles, only: [:update, :edit]
  resources :search, only: :index do
    collection do
      get 'paginate'
      get 'selected'
      get 'update_sub_categories'
    end
  end
  devise_for :users
  match "/about_us" => "static_pages#about_us", as: :about_us
  match "/contact_us" => "static_pages#contact_us", as: :contact_us
  match "/how_fpsm_works" => "static_pages#how_fpsm_works", as: :how_fpsm_works
  match "/submit_message" => "static_pages#submit_message", as: :submit_message, via: :post
  root to: 'static_pages#index'

  match 'auth/:provider/callback', to: 'authentications#create'
  match 'auth/failure', to: redirect('/')
  match 'signout', to: 'authentications#destroy', as: 'signout'
end

app/views/admin/_brands.html.erb
<% if @brands.any? %>
  <ul class="list-group">
    <% @brands.each do |brand| %>
      <li class="list-group-item">
        <%= brand.name %>
        <small><%= time_ago_in_words(brand.created_at) %></small>
      </li>
    <% end %>
  </ul>
<% else %>
  <div class="alert alert-info alert-dismissable">
    <button type="button" class="close" data-dismiss="alert"></button>
    <strong>No existe una marca todavía.</strong>
  </div>
<% end %>

app/views/admin/_categories.html.erb
<% if @categories.any? %>
  <ul class="list-group">
    <% @categories.each do |category| %>
      <li class="list-group-item">
        <%= category.name %>
        <small><%= time_ago_in_words(category.created_at) %></small>
      </li>
    <% end %>
  </ul>
<% else %>
  <div class="alert alert-info alert-dismissable">
    <button type="button" class="close" data-dismiss="alert"></button>
    <strong>No existe una categoría todavía.</strong>
  </div>
<% end %>

app/views/admin/_gondolas.html.erb
<% if @gondolas.any? %>
  <ul class="list-group">
    <% @gondolas.each do |gondola| %>
      <li class="list-group-item">
        <%= gondola.code_name %>
        <small><%= time_ago_in_words(gondola.created_at) %></small>
      </li>
    <% end %>
  </ul>
<% else %>
  <div class="alert alert-info alert-dismissable">
    <button type="button" class="close" data-dismiss="alert"></button>
    <strong>No existe una gondola todavía.</strong>
  </div>
<% end %>

app/views/admin/_messages.html.erb
<% if @messages.any? %>
  <ul class="list-group">
    <% @messages.each do |message| %>
      <li class="list-group-item">
        <%= message.subject %>
        <small><%= time_ago_in_words(message.created_at) %></small>
      </li>
    <% end %>
  </ul>
<% else %>
  <div class="alert alert-info alert-dismissable">
    <button type="button" class="close" data-dismiss="alert"></button>
    <strong>No existe un mensaje todavía.</strong>
  </div>
<% end %>

app/views/admin/_products.html.erb
<% if @products.any? %>
  <ul class="list-group">
    <% @products.each do |product| %>
      <li class="list-group-item">
        <%= image_tag product.link.present? ? product.link : product.photo, class: "img-rounded size90 mr10" %>
        <%= product.name %>
        <small><%= time_ago_in_words(product.created_at) %></small>
      </li>
    <% end %>
  </ul>
<% else %>
  <div class="alert alert-info alert-dismissable">
    <button type="button" class="close" data-dismiss="alert"></button>
    <strong>No existe un producto todavía.</strong>
  </div>
<% end %>

app/views/admin/_users.html.erb
<% if @users.any? %>
  <ul class="list-group">
    <% @users.each do |user| %>
      <li class="list-group-item">
        <%= image_tag user.person_profile.photo, class: "img-rounded size90 mr10" %>
        <%= user.person_profile.full_name %>
        <small><%= time_ago_in_words(user.created_at) %></small>
      </li>
    <% end %>
  </ul>
<% else %>
  <div class="alert alert-info alert-dismissable">
    <button type="button" class="close" data-dismiss="alert"></button>
    <strong>No existe un usuario todavía.</strong>
  </div>
<% end %>

app/views/admin/_worlds.html.erb
<% if @worlds.any? %>
  <ul class="list-group">
    <% @worlds.each do |world| %>
      <li class="list-group-item">
        <%= world.name %>
        <small><%= time_ago_in_words(world.created_at) %></small>
      </li>
    <% end %>
  </ul>
<% else %>
  <div class="alert alert-info alert-dismissable">
    <button type="button" class="close" data-dismiss="alert"></button>
    <strong>No existe un mundo todavía.</strong>
  </div>
<% end %>

app/views/admin/brands.html.erb
<%= stylesheet "/stylesheets/admin.css" %>
<div class="row content">
  <h4><%= page_entries_info @brands %></h4>
  <div class="mb20">
    <%= link_to new_brand_path, class: "btn btn-success" do %>
      <i class="glyphicon glyphicon-plus"></i>
      Nueva Marca
    <% end %>
  </div>
  <% if @brands.any? %>
    <div class="table-responsive">
      <table class="table table-bordered">
        <thead>
          <tr>
            <th>Nombre</th>
            <th>Acciones</th>
          </tr>
        </thead>
        <tbody class="table-hover">
          <% @brands.each do |brand| %>
            <tr>
              <td><%= brand.name %></td>
              <td>
                <%= link_to edit_brand_path(brand), class: "btn btn-warning" do %>
                  <i class="glyphicon glyphicon-pencil"></i>
                  Editar
                <% end %>
                <%= link_to brand, method: :delete, data: { confirm: '¿Estás seguro?' }, class: "btn btn-danger" do %>
                  <i class="glyphicon glyphicon-remove"></i>
                  Eliminar
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <%= paginate @brands %>
  <% end %>
</div>

app/views/admin/categories.html.erb
<%= stylesheet "/stylesheets/admin.css" %>
<div class="row content">
  <h4><%= page_entries_info @categories %></h4>
  <div class="mb20">
    <%= link_to new_category_path, class: "btn btn-success" do %>
      <i class="glyphicon glyphicon-plus"></i>
      Nueva Categoría
    <% end %>
  </div>
  <% if @categories.any? %>
    <div class="table-responsive">
      <table class="table table-bordered">
        <thead>
          <tr>
            <th>Nombre</th>
            <th>Mundo</th>
            <th>Acciones</th>
          </tr>
        </thead>
        <tbody class="table-hover">
          <% @categories.each do |category| %>
            <tr>
              <td><%= category.name %></td>
              <td><%= category.world.name %></td>
              <td>
                <%= link_to edit_category_path(category), class: "btn btn-warning" do %>
                  <i class="glyphicon glyphicon-pencil"></i>
                  Editar
                <% end %>
                <%= link_to category, method: :delete, data: { confirm: '¿Estás seguro?' }, class: "btn btn-danger" do %>
                  <i class="glyphicon glyphicon-remove"></i>
                  Eliminar
                <% end %>
                <%= link_to category_sub_categories_path(category), class: "btn btn-info" do %>
                  <i class="glyphicon glyphicon-list"></i>
                  Ver Sub Categorias
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <%= paginate @categories %>
  <% end %>
</div>

app/views/admin/gondolas.html.erb
<%= stylesheet "/stylesheets/admin.css" %>
<div class="row content">
  <h4><%= page_entries_info @gondolas %></h4>
  <div class="mb20">
    <%= link_to new_gondola_path, class: "btn btn-success" do %>
      <i class="glyphicon glyphicon-plus"></i>
      Nueva Góndola
    <% end %>
  </div>
  <% if @gondolas.any? %>
    <div class="table-responsive">
      <table class="table table-bordered">
        <thead>
          <tr>
            <th>Nombre</th>
            <th>Pasillo</th>
            <th>Categoría</th>
            <th>Niveles</th>
            <th>Cuerpos</th>
            <th>Acciones</th>
          </tr>
        </thead>
        <tbody class="table-hover">
          <% @gondolas.each do |gondola| %>
            <tr>
              <td><%= gondola.name %></td>
              <td><%= gondola.aisle.name %></td>
              <td><%= gondola.category.name %></td>
              <td><%= gondola.rows_count %></td>
              <td><%= gondola.columns_count %></td>
              <td>
                <%= link_to gondola, class: "btn btn-info" do %>
                  <i class="glyphicon glyphicon-eye-open"></i>
                  Ver
                <% end %>
                <%= link_to edit_gondola_path(gondola), class: "btn btn-warning" do %>
                  <i class="glyphicon glyphicon-pencil"></i>
                  Editar
                <% end %>
                <%= link_to gondola, method: :delete, data: { confirm: '¿Estás seguro?' }, class: "btn btn-danger" do %>
                  <i class="glyphicon glyphicon-remove"></i>
                  Eliminar
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <%= paginate @gondolas %>
  <% end %>
</div>

app/views/admin/index.html.erb
<%= javascript "/javascripts/admin.js" %>
<%= stylesheet "/stylesheets/admin.css" %>
<div class="content" id="admin-panel">
  <div class="row">
    <div class="col-lg-12 col-md-12 col-xs-12">
      <div class="panel panel-default">
         <div class="panel-heading">
          <%= link_to association_rules_path, class: "btn btn-info fr" do %>
            <i class="glyphicon glyphicon-list"></i>
            Ver todas
          <% end %>
          <h4>Reglas de Asociación de Productos</h4>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-6 col-md-6 col-xs-12">
      <div class="panel panel-default">
        <div class="panel-heading">
          <%= link_to users_admin_index_path, class: "btn btn-info fr" do %>
            <i class="glyphicon glyphicon-list"></i>
            Ver todos
          <% end %>
          <h4>Nuevos Usuarios</h4>
        </div>
        <div class="panel-body" id="new_users" data-target="<%= users_admin_index_url(format: :js) %>">
          <div class="badge badge-info">
            <i class="icon-white icon-time"></i>
            Cargando
          </div>
        </div>
      </div>
    </div>
    <div class="col-lg-6 col-md-6 col-xs-12">
      <div class="panel panel-default">
        <div class="panel-heading">
          <%= link_to messages_admin_index_path, class: "btn btn-info fr" do %>
            <i class="glyphicon glyphicon-list"></i>
            Ver todos
          <% end %>
          <h4>Nuevos Mensajes</h4>
        </div>
        <div class="panel-body" id="new_messages" data-target="<%= messages_admin_index_url(format: :js) %>">
          <div class="badge badge-info">
            <i class="icon-white icon-time"></i>
            Cargando
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-6 col-md-6 col-xs-12">
      <div class="panel panel-default">
        <div class="panel-heading">
          <%= link_to supermarkets_admin_index_path, class: "btn btn-info fr" do %>
            <i class="glyphicon glyphicon-list"></i>
            Ver todos
          <% end %>
          <h4>Nuevos Supermercardos</h4>
        </div>
        <div class="panel-body" id="new_supermarkets" data-target="<%= supermarkets_admin_index_url(format: :js) %>">
          <div class="badge badge-info">
            <i class="icon-white icon-time"></i>
            Cargando
          </div>
        </div>
        <div class="panel-footer">
          <%= link_to new_supermarket_path, class: "btn btn-success" do %>
            <i class="glyphicon glyphicon-plus"></i>
            Nuevo Supermercado
          <% end %>
        </div>
      </div>
    </div>
    <div class="col-lg-6 col-md-6 col-xs-12">
      <div class="panel panel-default">
        <div class="panel-heading">
          <%= link_to worlds_admin_index_path, class: "btn btn-info fr" do %>
            <i class="glyphicon glyphicon-list"></i>
            Ver todos
          <% end %>
          <h4>Nuevos Mundos</h4>
        </div>
        <div class="panel-body" id="new_worlds" data-target="<%= worlds_admin_index_url(format: :js) %>">
          <div class="badge badge-info">
            <i class="icon-white icon-time"></i>
            Cargando
          </div>
        </div>
        <div class="panel-footer">
          <%= link_to new_world_path, class: "btn btn-success" do %>
            <i class="glyphicon glyphicon-plus"></i>
            Nuevo Mundo
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-6 col-md-6 col-xs-12">
      <div class="panel panel-default">
        <div class="panel-heading">
          <%= link_to categories_admin_index_path, class: "btn btn-info fr" do %>
            <i class="glyphicon glyphicon-list"></i>
            Ver todas
          <% end %>
          <h4>Nuevas Categorias</h4>
        </div>
        <div class="panel-body" id="new_categories" data-target="<%= categories_admin_index_url(format: :js) %>">
          <div class="badge badge-info">
            <i class="icon-white icon-time"></i>
            Cargando
          </div>
        </div>
        <div class="panel-footer">
          <%= link_to new_category_path, class: "btn btn-success" do %>
            <i class="glyphicon glyphicon-plus"></i>
            Nueva Categoría
          <% end %>
        </div>
      </div>
    </div>
    <div class="col-lg-6 col-md-6 col-xs-12">
      <div class="panel panel-default">
        <div class="panel-heading">
          <%= link_to gondolas_admin_index_path, class: "btn btn-info fr" do %>
            <i class="glyphicon glyphicon-list"></i>
            Ver todas
          <% end %>
          <h4>Nuevas Góndolas</h4>
        </div>
        <div class="panel-body" id="new_gondolas" data-target="<%= gondolas_admin_index_url(format: :js) %>">
          <div class="badge badge-info">
            <i class="icon-white icon-time"></i>
            Cargando
          </div>
        </div>
        <div class="panel-footer">
          <%= link_to new_gondola_path, class: "btn btn-success" do %>
            <i class="glyphicon glyphicon-plus"></i>
            Nueva Góndola
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-6 col-md-6 col-xs-12">
      <div class="panel panel-default">
        <div class="panel-heading">
          <%= link_to brands_admin_index_path, class: "btn btn-info fr" do %>
            <i class="glyphicon glyphicon-list"></i>
            Ver todas
          <% end %>
          <h4>Nuevas Marcas</h4>
        </div>
        <div class="panel-body" id="new_brands" data-target="<%= brands_admin_index_url(format: :js) %>">
          <div class="badge badge-info">
            <i class="icon-white icon-time"></i>
            Cargando
          </div>
        </div>
        <div class="panel-footer">
          <%= link_to new_brand_path, class: "btn btn-success" do %>
            <i class="glyphicon glyphicon-plus"></i>
            Nueva Marca
          <% end %>
        </div>
      </div>
    </div>
    <div class="col-lg-6 col-md-6 col-xs-12">
      <div class="panel panel-default">
        <div class="panel-heading">
          <%= link_to products_admin_index_path, class: "btn btn-info fr" do %>
            <i class="glyphicon glyphicon-list"></i>
            Ver todos
          <% end %>
          <h4>Nuevos Productos</h4>
        </div>
        <div class="panel-body" id="new_products" data-target="<%= products_admin_index_url(format: :js) %>">
          <div class="badge badge-info">
            <i class="icon-white icon-time"></i>
            Cargando
          </div>
        </div>
        <div class="panel-footer">
          <%= link_to new_product_path, class: "btn btn-success" do %>
            <i class="glyphicon glyphicon-plus"></i>
            Nuevo Producto
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/products.html.erb
<%= stylesheet "/stylesheets/admin.css" %>
<div class="row content">
  <h4><%= page_entries_info @products %></h4>
  <div class="mb20">
    <%= link_to new_product_path, class: "btn btn-success" do %>
      <i class="glyphicon glyphicon-plus"></i>
      Nuevo Producto
    <% end %>
  </div>
  <% if @products.any? %>
    <div class="table-responsive">
      <table class="table table-bordered">
        <thead>
          <tr>
            <th>Nombre</th>
            <th>Categoría - Sub Categoría</th>
            <th>Marca</th>
            <th>Acciones</th>
          </tr>
        </thead>
        <tbody class="table-hover">
          <% @products.each do |product| %>
            <tr>
              <td>
                <%= image_tag product.link.present? ? product.link : product.photo, class: "size40 mr10" %>
                <%= product.name %>
              </td>
              <td><%= product.category_sub_category %></td>
              <td><%= product.brand.name %></td>
              <td>
                <%= link_to product, class: "btn btn-info" do %>
                  <i class="glyphicon glyphicon-eye-open"></i>
                  Ver
                <% end %>
                <%= link_to edit_product_path(product), class: "btn btn-warning" do %>
                  <i class="glyphicon glyphicon-pencil"></i>
                  Editar
                <% end %>
                <%= link_to product, method: :delete, data: { confirm: '¿Estás seguro?' }, class: "btn btn-danger" do %>
                  <i class="glyphicon glyphicon-remove"></i>
                  Eliminar
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <%= paginate @products %>
  <% end %>
</div>

app/views/admin/users.html.erb
<%= stylesheet "/stylesheets/admin.css" %>
<div class="row content">
  <h4><%= page_entries_info @users %></h4>
  <% if @users.any? %>
    <div class="table-responsive">
      <table class="table table-bordered">
        <thead>
          <tr>
            <th>Nombre Completo</th>
            <th>Correo</th>
            <th>Número de sesiones</th>
          </tr>
        </thead>
        <tbody class="table-hover">
          <% @users.each do |user| %>
            <tr>
              <td>
                <%= image_tag user.person_profile.photo, class: "size40 mr10" %>
                <%= user.person_profile.full_name %>
              </td>
              <td><%= user.email %></td>
              <td><%= user.sign_in_count %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <%= paginate @users %>
  <% end %>
</div>

app/views/admin/worlds.html.erb
<%= stylesheet "/stylesheets/admin.css" %>
<div class="row content">
  <h4><%= page_entries_info @worlds %></h4>
  <div class="mb20">
    <%= link_to new_world_path, class: "btn btn-success" do %>
      <i class="glyphicon glyphicon-plus"></i>
      Nuevo Mundo
    <% end %>
  </div>
  <% if @worlds.any? %>
    <table class="table table-bordered">
      <thead>
        <tr>
          <th>Nombre</th>
          <th>Acciones</th>
        </tr>
      </thead>
      <tbody class="table-hover">
        <% @worlds.each do |world| %>
          <tr>
            <td><%= world.name %></td>
            <td>
              <%= link_to edit_world_path(world), class: "btn btn-warning" do %>
                <i class="glyphicon glyphicon-pencil"></i>
                Editar
              <% end %>
              <%= link_to world, method: :delete, data: { confirm: '¿Estás seguro?' }, class: "btn btn-danger" do %>
                <i class="glyphicon glyphicon-remove"></i>
                Eliminar
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <%= paginate @worlds %>
  <% end %>
</div>