config/routes.rb
FinderProductsSupermarket::Application.routes.draw do
  resources :cart, only: :show do
    put 'add_to/:product_supermarket_id', to: 'cart#add', as: :add_to
    put 'remove_from/:product_supermarket_id', to: 'cart#remove', as: :remove_from
    collection do
      get 'product_supermarkets_selected'
    end
  end
  resources :supermarkets do
    resources :aisles, except: :show
  end
  resources :brands, except: [:show, :index]
  resources :worlds, except: [:show, :index]
  resources :finder_products, only: :index do
    match "/new" => "finder_products#new", via: :post, on: :collection
    collection do
      get "selected"
      get "suggested"
      get "show_product_in_gondola"
      get "in_cart"
    end
  end
  resources :association_rules do
    member do
      get 'flare'
      get 'paginate'
      get 'show_products_in_layout'
      get 'paths'
    end
  end
  resources :lists, only: [:index, :create] do
    match "/new" => "lists#new", via: :post, on: :collection
    match "/destroy" => "lists#destroy", via: :delete, on: :member
    match "/add_products" => "lists#add_products", via: :put, on: :collection
    match "/destroy_product" => "lists#destroy_product", via: :delete, on: :collection
  end
  resources :gondolas, except: :index do
    collection do
      get 'points_from'
    end
  end
  resources :products, except: :index do
    resources :gondola_products, except: :show
    resources :product_supermarkets, except: :show
  end
  resources :categories, except: [:show, :index] do
    resources :sub_categories, except: :show
    member do
      get 'update_sub_categories'
    end
  end
  resources :admin, only: :index do
    collection do
      get 'users'
      get 'categories'
      get 'aisles'
      get 'gondolas'
      get 'products'
      get 'worlds'
      get 'brands'
      get 'supermarkets'
      get 'messages'
      get 'message'
    end
  end
  resources :person_profiles, only: [:update, :edit]
  resources :search, only: :index do
    collection do
      get 'paginate'
      get 'selected'
      get 'update_sub_categories'
    end
  end
  devise_for :users
  match "/about_us" => "static_pages#about_us", as: :about_us
  match "/contact_us" => "static_pages#contact_us", as: :contact_us
  match "/how_fpsm_works" => "static_pages#how_fpsm_works", as: :how_fpsm_works
  match "/submit_message" => "static_pages#submit_message", as: :submit_message, via: :post
  root to: 'static_pages#index'

  match 'auth/:provider/callback', to: 'authentications#create'
  match 'auth/failure', to: redirect('/')
  match 'signout', to: 'authentications#destroy', as: 'signout'
end

app/models/sub_category.rb
class SubCategory < ActiveRecord::Base
  attr_accessible :category_id, :name, :state

  has_many :products
  belongs_to :category

  paginates_per 10

  validates_presence_of :name, :category_id
end

app/controllers/sub_categories_controller.rb
class SubCategoriesController < ApplicationController
  layout 'admin'

  before_filter :authenticate_user!
  before_filter :only_admin
  before_filter :find_category

  def index
    @sub_categories = @category.sub_categories.page(params[:page])
  end

  def new
    @sub_category = SubCategory.new
  end

  def edit
    @sub_category = SubCategory.find(params[:id])
  end

  def create
    @sub_category = @category.sub_categories.build(params[:sub_category])

    if @sub_category.save
      flash[:notice] = "Sub Categoria #{ @sub_category.name } para #{ @category.name } fue satisfactoriamente creada."
      redirect_to category_sub_categories_path(@category)
    else
      render action: "new"
    end
  end

  def update
    @sub_category = SubCategory.find(params[:id])

    if @sub_category.update_attributes(params[:sub_category])
      flash[:notice] = "Sub Categoria #{ @sub_category.name } para #{ @category.name } fue satisfactoriamente actualizada."
      redirect_to category_sub_categories_path(@category)
    else
      render action: "edit"
    end
  end

  def destroy
    @sub_category = SubCategory.find(params[:id])
    @sub_category.destroy

    flash[:notice] = "Sub Categoria #{ @sub_category.name } para #{ @category.name } fue satisfactoriamente eliminada."
    redirect_to category_sub_categories_path(@category)
  end

  private

  def find_category
    @category = Category.find(params[:category_id])
  end
end

app/helpers/sub_categories_helper.rb
module SubCategoriesHelper
end

app/views/sub_categories/_form.html.erb
<%= form_for([@category, @sub_category], html: { role: "form", class: "form-horizontal" }) do |f| %>
  <%= error_messages!(@sub_category) %>
  <div class="form-group">
    <div class="col-sm-12">
      <%= f.text_field :name, autofocus: true, class: "form-control", placeholder: "Nombre" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-12">
      <div class="checkbox">
        <label>
          <%= f.check_box :state %>
          Activo
        </label>
      </div>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-12">
      <%= button_tag class: "btn btn-default", type: "submit" do %>
        <i class="glyphicon glyphicon-floppy-disk"></i>
        Guardar
      <% end %>
      <%= link_to category_sub_categories_path(@category), class: "btn btn-info" do %>
        <i class="glyphicon glyphicon-arrow-left"></i>
        Regresar
      <% end %>
    </div>
  </div>
<% end %>

app/views/sub_categories/edit.html.erb
<%= stylesheet "/stylesheets/admin.css" %>
<div class="row content">
  <div class="col-md-offset-3 col-md-6">
    <h3>Editando Sub Categoría</h3>
    <%= render 'form' %>
  </div>
</div>

app/views/sub_categories/index.html.erb
<%= stylesheet "/stylesheets/admin.css" %>
<div class="row content">
  <h4><%= page_entries_info @sub_categories %> <%= "de #{ @category.name }" %></h4>
  <div class="mb20">
    <%= link_to new_category_sub_category_path(@category), class: "btn btn-success" do %>
      <i class="glyphicon glyphicon-plus"></i>
      Nueva Sub Categoría
    <% end %>
    <%= link_to categories_admin_index_path, class: "btn btn-info" do %>
      <i class="glyphicon glyphicon-arrow-left"></i>
      Regresar
    <% end %>
  </div>
  <% if @sub_categories.any? %>
    <div class="table-responsive">
      <table class="table table-bordered">
        <thead>
          <tr>
            <th>Nombre</th>
            <th>Acciones</th>
          </tr>
        </thead>
        <tbody class="table-hover">
          <% @sub_categories.each do |sub_category| %>
            <tr>
              <td><%= sub_category.name %></td>
              <td>
                <%= link_to edit_category_sub_category_path(@category, sub_category), class: "btn btn-warning" do %>
                  <i class="glyphicon glyphicon-pencil"></i>
                  Editar
                <% end %>
                <%= link_to category_sub_category_path(@category, sub_category), method: :delete, data: { confirm: '¿Estás seguro?' }, class: "btn btn-danger" do %>
                  <i class="glyphicon glyphicon-remove"></i>
                  Eliminar
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <%= paginate @sub_categories %>
  <% end %>
</div>

app/views/sub_categories/new.html.erb
<%= stylesheet "/stylesheets/admin.css" %>
<div class="row content">
  <div class="col-md-offset-3 col-md-6">
    <h3>Nueva Sub Categoría</h3>
    <%= render 'form' %>
  </div>
</div>